print "Newline escape sequence \newline"
print "Backslash \\"
print "\'Single Quote\'"
print "\"Double Quotes\""
print "Bell \a !!"
print "Backspace \b !!"
print "Formfeed \f !!"
print "Linefeed \n !!"
print "Carriage Return \r !!"
print "Horizontal Tab \t !!"
print "Vertical Tab \v !!"
