str = raw_input("Enter the string: ")
print "Capitalize: ", str.capitalize()
print "Center ",str.center(40,'a')
findstr = raw_input("Enter String to search: ")
str2=str.encode('UTF-8','strict')
print "Encode: ",str2
print "Decode: ",str2.decode('UTF-8','strict')
print "Endswith ",str.endswith(findstr, 0, len(str))
print "Tabspaces: ",str.expandtabs(8)
print "Find: ",str.find(findstr,0,len(str))
print "Is alnum: ",str.isalnum()
print "Is alphabet: ",str.isalpha()
print "Is digit: ",str.isdigit()
print "Is lowercase: ",str.islower()
print "Is space: ",str.isspace()
print "Is title: ",str.istitle()
print "Is uppercase: ",str.isupper()
print "Join: ",str.join(findstr)
print "Length: ",len(str)
print "Convert to lowercase: ",str.lower()
print "Remove leading white spaces: ",str.lstrip()
print "Max: ",max(str)
print "Min: ",min(str)
print "Replace: ",str.replace("e","@")
print "Backwards search: ",str.rfind(findstr,0,len(str))
print "Right Pad: ",str.rjust(4,"0")
print "Remove trailing whitespace: ",str.rstrip()
print "Split string: ",str.split(" ")
print "Split lines: ",str.splitlines(str.count('\n'))
print "Starts With: ",str.startswith("H",0,len(str))
print "Swap Case: ",str.swapcase()
print "Title Case: ",str.title()
print "Upper Case: ",str.upper()
print "Zero pad: ",str.zfill(4)

