tupday=("Monday","Tuesday","Wednesday","Thursday","Friday")
tupmonth=("January","February","March","April","May","June","July","August","September","October","November","December")
print "Comparing: ",cmp(tupday,tupmonth)
print "Length: ",len(tupday)
print "Maxvalue: ",max(tupday)
print "Minvalue: ",min(tupday)
print "Tuple as list: ",list(tupday)
