fo = open("example.txt","r")
print fo.read()
fo.close()
fo = open("example2.txt","w")
fo.write("This is writing to a file.\n Congratulations on writing to a file!\n This is the fourth line. \n This is the fifth line")
fo.close()
fo = open("example.txt","a")
print fo.write("Line1\nLine2\nLine3\nLine4\nLine5")
fo.close()
